AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM deployment file for PlastepProductInformationServices in native mode
Globals:
  Api:
    EndpointConfiguration: REGIONAL
    BinaryMediaTypes:
      - "*/*"

Resources:
  PlastepProductInformationServices:
    Type: AWS::Serverless::Function
    Properties:
      Handler: not.used.in.provided.runtime
      Runtime: provided
      CodeUri: ../../../build/function.zip
      MemorySize: 128
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 120
      Environment:
        Variables:
          DISABLE_SIGNAL_HANDLERS: true
      Events:
        HttpApiEvent:
          Type: HttpApi

Outputs:
  PlastepProductInformationServicesApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/'
    Export:
      Name: PlastepProductInformationServicesApi
