AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM deployment file for PlastepProductInformationServices in native mode
Globals:
  Api:
    EndpointConfiguration: REGIONAL
    BinaryMediaTypes:
      - "*/*"

Resources:
  PlastepProductInformationServices:
    Type: AWS::Serverless::Function
    Properties:
      Handler: not.used.in.provided.runtime
      Runtime: provided
      CodeUri: ../../../build/function.zip
      MemorySize: 128
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 120
      Environment:
        Variables:
          DISABLE_SIGNAL_HANDLERS: true
      Events:
        HttpApiEvent:
          Type: HttpApi

  # PlastepProductInformationFiles:
  #   Type: AWS::S3::Bucket

  # PlastepProductInformationFilesBucketAllowPublicReadPolicy:
  #   Type: AWS::S3::BucketPolicy
  #   Properties:
  #     Bucket: !Ref PlastepProductInformationFiles
  #     PolicyDocument:
  #       Version: "2012-10-17"
  #       Statement:
  #         - Effect: Allow
  #           Action:
  #             - s3:PutObject
  #             - s3:GetObject
  #             - s3:PutObjectAcl
  #           Resource: !Join
  #             - ''
  #             - - 'arn:aws:s3:::'
  #               - !Ref PlastepProductInformationFiles
  #               - /*
  #           Principal: "*"
  #         - Effect: Allow
  #           Action:
  #             - s3:ListBucket
  #             - s3:GetBucketLocation
  #           Resource: !Join
  #             - ''
  #             - - 'arn:aws:s3:::'
  #               - !Ref PlastepProductInformationFiles
  #           Principal: "*"

  # PlastepProductInformationFilesIAMUser:
  #   Type: AWS::IAM::User
  #   Properties:
  #     Path: "/"
  #     Policies:
  #       - PolicyName: allow-s3
  #         PolicyDocument:
  #           Version: '2012-10-17'
  #           Statement:
  #             - Effect: Allow
  #               Action:
  #                 - s3:*
  #               Resource: !Join
  #                 - ''
  #                 - - 'arn:aws:s3:::'
  #                   - !Ref PlastepProductInformationFiles
  #                   - /*

  # PlastepProductInformationFilesIAMUserAccessKey:
  #   Type: AWS::IAM::AccessKey
  #   Properties:
  #     UserName:
  #       !Ref PlastepProductInformationFilesIAMUser

Outputs:
  PlastepProductInformationServicesApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/'
    Export:
      Name: PlastepProductInformationServicesApi
